spring:
  main:
    banner-mode: "off"
vertx:
  worker-pool-size: 300
  uploads-dir: file-uploads
  verticle:
    deploy-timeout-ms: 15000
    instances: 4
http:
  port: 8080
http-client:
  max-pool-size: 8196
  connect-timeout-ms: 1000
